export const items = [
    {
      category: "bungee",
      name: "Bungee Jumping",
      price: "99.99",
      description: "Thrilling jumps from incredible heights!",
      image: "https://res.cloudinary.com/manawa/image/upload/f_auto,c_limit,w_3840,q_auto/articles/61467/London_BungeeJumping_TheUKBungee_3_i6gsup",
    },
    {
      category: "rafting",
      name: "White Water Rafting",
      price: "79.99",
      description: "Conquer rapids, feel the rush!",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Rafting_em_Brotas.jpg/1200px-Rafting_em_Brotas.jpg",
    },
    {
      category: "drifting",
      name: "Drift Racing",
      price: "149.99",
      description: "Pro drift experience, adrenaline rush!",
      image: "https://img.redbull.com/images/c_limit,w_1500,h_1000,f_auto,q_auto/redbullcom/2023/3/11/vh10bj8ttqxisaneqcv5/elias-and-joe-hountondji-drift-racing",
    },
    {
      category: "airballoon",
      name: "Hot Air Balloon",
      price: "199.99",
      description: "Float above, breathtaking views!",
      image: "https://media.tacdn.com/media/attractions-splice-spp-674x446/07/3c/cf/f5.jpg",
    },
    {
      category: "diving",
      name: "Scuba Diving",
      price: "129.99",
      description: "Explore underwater, marine wonders!",
      image: "https://www.planctondiving.cat/wp-content/uploads/2020/07/plancton-diving-submarinisme-bateig-ametlla-catalunya-cursos-scaled.jpg",
    },
    {
      category: "parachute",
      name: "Tandem Parachute",
      price: "149.99",
      description: "Adrenaline, tandem skydive!",
      image: "https://images.virginexperiencedays.co.uk/images/product/large/parachute-jump-31163223.jpg?auto=compress,format",
    },
    {
      category: "bungee",
      name: "Extreme Bungee Jump",
      price: "149.99",
      description: "Daredevil jump, insanely high platform!",
      image: "https://res.klook.com/images/fl_lossy.progressive,q_65/c_fill,w_1349,h_1080,f_auto/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/uhpfpky1wszzbpgfhwux/BungeeJumpinPokhara,Nepal-KlookUnitedStates.jpg",
    },
    {
      category: "rafting",
      name: "Wild River Rafting",
      price: "89.99",
      description: "Navigate untamed waters, unforgettable!",
      image: "https://rafting.bg/wp-content/uploads/2016/04/rafting-spuskane-reka-struma-rafting-bg-2.jpg",
    },
    {
      category: "drifting",
      name: "Pro Drift Racing",
      price: "199.99",
      description: "Race like a pro, controlled track!",
      image: "https://upload.wikimedia.org/wikipedia/commons/9/9f/King_of_Europe_Round_3_Lydden_Hill_2014_%2814356011899%29.jpg",
    },
    {
      category: "airballoon",
      name: "Sunrise Balloon Ride",
      price: "219.99",
      description: "Tranquil sunrise ride, stunning views!",
      image: "https://cdn.freedome.it/o/1920/listing/volo-in-mongolfiera-allalba-sul-borgo-medievale-di-cittadella-pd-6.jpeg",
    },
    {
      category: "diving",
      name: "Deep Sea Diving",
      price: "159.99",
      description: "Explore deep, witness marine wonders!",
      image: "https://media.istockphoto.com/id/498283106/photo/underwater-scuba-diver-explore-and-enjoy-coral-reef-sea-life.jpg?s=612x612&w=0&k=20&c=xOj00xaZTpy5-AtKvMvIHHfexz9miSSct_CXb6F9KVA=",
    },
    {
      category: "parachute",
      name: "High Altitude Jump",
      price: "199.99",
      description: "Jump from altitude, adrenaline rush!",
      image: "https://www.skydiving.co.uk/wp-content/uploads/sh-tandem-freefall-1200x1200-cropped.jpg",
    },
    {
      category: "bungee",
      name: "Urban Bungee Jump",
      price: "119.99",
      description: "City thrill, jump from iconic locations!",
      image: "https://transcode-v2.app.engoo.com/image/fetch/f_auto,c_lfill,w_300,dpr_3/https://assets.app.engoo.com/images/2fx5wl2ILeIEGbEgd96OTF.jpeg",
    },
    {
      category: "rafting",
      name: "Rafting Expedition",
      price: "99.99",
      description: "Expedition, conquer challenging rapids!",
      image: "https://teambuilding-bg.com/wp-content/uploads/2020/11/struma-rafting-x-club-3.png",
    },
    {
      category: "drifting",
      name: "Adrenaline Drifting",
      price: "169.99",
      description: "Adrenaline-packed drifting, push the limits!",
      image: "https://www.motorbiscuit.com/wp-content/uploads/2022/01/racecar-drifting.jpg",
    },
    {
      category: "airballoon",
      name: "Balloon Flight",
      price: "179.99",
      description: "Gentle flight, scenic beauty!",
      image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/de/f3/66/ontario-hot-air-balloon.jpg?w=1200&h=1200&s=1",
    },
    {
      category: "diving",
      name: "Coral Reef Dive",
      price: "139.99",
      description: "Dive, explore vibrant coral reefs!",
      image: "https://www.greenqueen.com.hk/wp-content/uploads/2019/04/zublu_bali-3.jpg",
    },
    {
      category: "parachute",
      name: "Solo Parachute Jump",
      price: "179.99",
      description: "Solo jump, feel the freedom!",
      image: "https://ukskydiving.com/wp-content/uploads/2018/10/parchutejumping-1.jpg",
    },
    {
      category: "parachute",
      name: "Solo Parachute Jump",
      price: "179.99",
      description: "Solo jump, feel the freedom!",
      image: "https://ukskydiving.com/wp-content/uploads/2018/10/parchutejumping-1.jpg",
    },
    {
      category: "parachute",
      name: "Solo Parachute Jump",
      price: "179.99",
      description: "Solo jump, feel the freedom!",
      image: "https://ukskydiving.com/wp-content/uploads/2018/10/parchutejumping-1.jpg",
    },
  ];
  